name: .NET Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build Tombatron.Results
        run: dotnet build Tombatron.Results/Tombatron.Results.csproj
        
      - name: Build Tombatron.Results.Analyzers
        run: dotnet build Tombatron.Results.Analyzers/Tombatron.Results.Analyzers/Tombatron.Results.Analyzers.csproj
        
      - name: Run Tests
        run: dotnet test .\Tombatron.Results.Analyzers\Tombatron.Results.Analyzers.Tests\Tombatron.Results.Analyzers.Tests.csproj --no-build